version: "1"
name: "dev-enkya"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev-enkya-web
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/enkya-blog
      - /var/www/enkya-blog/node_modules
    environment:
      - TIER=dev
